# Generated by Django 5.1.2 on 2024-10-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="user_pics/"),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="bio",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
