# Generated by Django 5.1.2 on 2024-11-05 17:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="like_posts",
            new_name="likes",
        ),
    ]
