# Generated by Django 5.1.2 on 2024-11-06 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0002_delete_pagelike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="like_pages",
            new_name="likes",
        ),
    ]
