# Generated by Django 5.1.1 on 2024-11-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_notification_action_taken_post_tagged_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tagged_users',
        ),
    ]
