# Generated by Django 5.1.2 on 2024-11-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0002_paidcontent_purchase_vipsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidcontent",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="paid_content_images/"
            ),
        ),
    ]
