# Generated by Django 5.1.2 on 2024-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0002_alter_userprofileinfo_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/default.jpg", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
