# Generated by Django 5.1.1 on 2024-11-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0002_grouppost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='personal_posts/'),
        ),
    ]
