# Generated by Django 5.1.2 on 2024-11-06 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0003_rename_like_pages_page_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reactions",
            field=models.ManyToManyField(
                blank=True, related_name="reacted_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
