# Generated by Django 5.1.1 on 2024-11-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0003_remove_comment_content_type_comment_group_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='group_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='SocialMedia.grouppost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='SocialMedia.post'),
        ),
    ]
