# Generated by Django 5.1.2 on 2024-10-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0003_alter_userprofileinfo_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofileinfo",
            name="cover_photo",
            field=models.ImageField(blank=True, upload_to="cover_photos/"),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="user_pics/"),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="bio",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="userprofileinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
