# Generated by Django 5.1.1 on 2024-11-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_comments/'),
        ),
    ]
