# Generated by Django 5.1.2 on 2024-11-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("SocialMedia", "0006_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_mode",
            field=models.CharField(
                choices=[
                    ("public", "Công khai"),
                    ("private", "Riêng tư"),
                    ("only_me", "Chỉ tôi"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
