# Generated by Django 5.1.1 on 2024-11-17 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0008_remove_groupmember_joined_at_alter_groupmember_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMember',
            new_name='GroupMemberShip',
        ),
    ]
