# Generated by Django 5.1.1 on 2024-11-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_remove_joinrequest_created_at_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='SocialMedia.comment'),
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
