# Generated by Django 5.1.1 on 2024-11-17 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMedia', '0009_rename_groupmember_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', through='SocialMedia.GroupMemberShip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupcomment',
            name='group_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SocialMedia.grouppost'),
        ),
    ]
